baseurl = "https://luka.strizic.info/"
title = "Undefined Reference"
theme = "slender-custom"
defaultExtension = "html"
languageCode = "en-US"
metaDataFormat = "toml"
paginate = 10
paginatePath = "/"
defaultLayout = "post"
footnoteAnchorPrefix = ""
footnoteReturnLinkContents = "↑"
pygmentsStyle = "monokai"

watch = true
verbose = false
log = true
verboseLog = true
hasCJKLanguage = false
uglyURLs = false
stepAnalysis = false
pygmentsUseClasses = false
pluralizeListTitles = true
preserveTaxonomyNames = false
noTimes = false
disableLiveReload = true
disableRSS = false
disableSitemap = false
disablePathToLower = true
buildDrafts = false
buildFuture = false
relativeURLs = true
canonifyURLs = true

source = "/home/luka/blog"
config = "/home/luka/blog/config.toml"
archetypeDir = "/home/luka/blog/archetype"
contentDir = "/home/luka/blog/content"
dataDir = "/home/luka/blog/data"
layoutDir = "/home/luka/blog/layouts"
publishDir = "/home/luka/blog/public"
staticDir = "/home/luka/blog/static"
logFile = "/home/luka/caddy/hugo.log"

googleAnalytics = ""
editor = ""
newContentEditor = ""
ignoreFiles = [ "\\.foo$", "\\.boo$" ]

[permalinks]

    page = "/:title/"
    post = "/post/:title/"
	
[sitemap]

[taxonomies]
  # category = "categories"
  # tag = "tags"

[author]

    name = "Luka Strizic"

[params]
    # Description and keywords for <meta> tags.
    # Remember to set this for your main page.
    # This will be overridden by whatever is set by the page or post,
    # defined by `description` and `keywords` variables in the front matter
    # of the markdown file.
    description = "Technical blog about stuff I probably couldn't find elsewhere on the internet or about stuff I find fun to write about."
    keywords = ""

    # Tagline; HTML accepted here. Keep it concise.
    tagline = "to 'getBlogName()'"

    # Social links, must be full URLs (e.g. https://github.com/CrimsonRay/).
    # Remove, comment, or leave blank any field to leave them out.
    # Email generated using http://www.closetnoc.org/mungemaster/mungemaster.pl
    # and embedded in header.html
    # email = "mailto:luka@strizic.info"
    github = "https://www.github.com/lstrz"
    linkedin = "https://www.linkedin.com/in/lstrz"
    cv = "/LSCV.pdf"

    # Footer; Markdown accepted here.
    footer = '<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img height="24" width="24" alt="Creative Commons License" style="border-width:0" src="/assets/cc.svg" /></a> <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img height="24" width="24" alt="Creative Commons License" style="border-width:0" src="/assets/by.svg" /></a>'

    # Google Analytics
    # Remove, comment, or leave it blank if you don't have one.
    ganalytics = ""

[menu]

    # Menu for the nav bar.
    # There must always be one item present (e.g. home).
    [[menu.main]]
    identifier = "home"
    name       = "home"
    url        = ""
    weight     = 0

    [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "about/"
    weight     = 1

